# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Amanda Saffer - Front-End Developer and Designer
email: amandasaffer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Amanda Saffer is a web designer and developer from Denver, CO
  that loves helping small businesses and entrepreneurs bring 
  their ideas to life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ajsaffer.com" # the base hostname & protocol for your site
twitter_username: ajsaffer
github_username:  amandasaffer

collections:
  cases:
    output: true
    title: cases
    permalink: /cases/:path/

# Build settings
markdown: kramdown
